# Generated by Django 4.2.1 on 2023-06-23 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactos', '0002_alter_contactos_numero1_alter_contactos_numero2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactos',
            name='numero2',
        ),
        migrations.RemoveField(
            model_name='contactos',
            name='numero3',
        ),
        migrations.AlterField(
            model_name='contactos',
            name='grupo',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
