# Generated by Django 4.2.1 on 2023-06-28 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactos', '0003_remove_contactos_numero2_remove_contactos_numero3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactos',
            name='numero1',
        ),
        migrations.AddField(
            model_name='contactos',
            name='numero',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
