# Generated by Django 4.2.1 on 2023-06-29 17:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactos', '0004_remove_contactos_numero1_contactos_numero'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50)),
                ('apellido', models.CharField(blank=True, max_length=50)),
                ('numero', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('grupo', models.CharField(blank=True, max_length=50)),
                ('fecha_inclusion', models.DateField(default=datetime.date.today)),
                ('notas', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
