# Generated by Django 4.2.1 on 2023-06-12 21:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contactos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('lugar', models.CharField(max_length=100)),
                ('contacto_rel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contactos.contactos')),
            ],
        ),
    ]
