# Generated by Django 4.2.1 on 2023-06-29 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contactos', '0005_contacto'),
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='contacto_rel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contactos.contacto'),
        ),
    ]
