# Generated by Django 4.2.1 on 2023-06-29 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contactos', '0006_delete_contactos'),
        ('agenda', '0003_rename_eventos_evento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='contacto_rel',
        ),
        migrations.AddField(
            model_name='evento',
            name='contacto_relacionado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contactos.contacto'),
        ),
    ]
