# Generated by Django 4.2.1 on 2023-06-29 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contactos', '0006_delete_contactos'),
        ('agenda', '0004_remove_evento_contacto_rel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='contacto_relacionado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contactos.contacto'),
        ),
    ]
